import type { Metadata } from "next";
import { Inter, Meow_Script } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} >
        <div className="min-h-screen flex px-4 w-full">
          <div className="flex items-center border-r-2">
            <h1 className="font-extrabold mr-2 leading-relaxed">
              <span className="text-4xl">Whisker</span>
              <br />
              <span className="relative text-6xl">
                Wonderland
                <span
                  className="absolute
                                left-0
                                bottom-0
                                -z-10
                                h-6 w-full 
                                bg-amber-500"
                ></span>
              </span>
            </h1>
          </div>
          <div className="max-h-screen overflow-auto w-full ">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
